language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install twisted autobahn coveralls
script:
  - nosetests --with-coverage --cover-package=txasgiresource
after_success:
  - coveralls